// <auto-generated />
namespace BuyCafe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class fix_ProductCustomization_Model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix_ProductCustomization_Model));
        
        string IMigrationMetadata.Id
        {
            get { return "202408220335063_fix_ProductCustomization_Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
