// <auto-generated />
namespace BuyCafe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class fix_Model_OrderItemAdd_ProductId_And_ImagePath : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix_Model_OrderItemAdd_ProductId_And_ImagePath));
        
        string IMigrationMetadata.Id
        {
            get { return "202408280315000_fix_Model_OrderItem(Add_ProductId_And_ImagePath)"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
