// <auto-generated />
namespace BuyCafe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Updata_Model_Order_Columns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updata_Model_Order_Columns));
        
        string IMigrationMetadata.Id
        {
            get { return "202409060531214_Updata_Model_Order_Columns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
